syntax = "proto3";
import "google/protobuf/timestamp.proto";

package mypackage.SSC.common;

// Person message defines basic information about a person
message Person {
    // Name, required field, number 1
    string name = 1;

    // ID, required field, number 2
    int32 id = 2;

    // Birthday, required field, number 3
    string birthday = 3;

    // List of history records associated with the person
    repeated History history = 4; 
}

// History message defines basic information about a person's history
message History {

    int32 id = 1; // The unique identifier for the Person

    string email = 2; // The contact email of the person

    google.protobuf.Timestamp start_date = 3; // The start date of the history record

    google.protobuf.Timestamp end_date = 4; // The end date of the history record

    string level = 5; // The professional level or grade of the person during this period

    repeated string skills = 6; // List of skills possessed by the person

    repeated string languages = 7; // List of languages spoken by the person
}
